
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/res/res.js",
	"libs/modules/eui/eui.js",
	"libs/modules/tween/tween.js",
	"libs/modules/socket/socket.js",
	"polyfill/promise.js",
	"bin-debug/base/Base_MapUnit.js",
	"bin-debug/base/Base_module.js",
	"bin-debug/data/Enums.js",
	"bin-debug/data/proto/MessageHandle.js",
	"bin-debug/data/proto/Pro.js",
	"bin-debug/base/Base _view.js",
	"bin-debug/data/temple/Temple.js",
	"bin-debug/utils/Dictionary.js",
	"bin-debug/data/temple/GlobalDefineTemple.js",
	"bin-debug/components/bag/equipPop/Attr_GemInfo.js",
	"bin-debug/components/bag/equipPop/Bag_attrItem.js",
	"bin-debug/components/bag/equipPop/Bag_itemInfo.js",
	"bin-debug/components/bag/GoodsItem.js",
	"bin-debug/components/bag/goodsPop/Attr_goodsItem.js",
	"bin-debug/components/bag/goodsPop/Attr_goodsUse.js",
	"bin-debug/components/bag/goodsPop/Pop_goodsInfo.js",
	"bin-debug/components/bag/Smelt_selectItem.js",
	"bin-debug/components/boss/Boss_award.js",
	"bin-debug/components/boss/Boss_personal_item.js",
	"bin-debug/components/boss/Boss_personal_tab.js",
	"bin-debug/components/boss/Boss_world_tab.js",
	"bin-debug/components/btn/Btn1.js",
	"bin-debug/components/btn/Btn2.js",
	"bin-debug/components/btn/Btn3.js",
	"bin-debug/components/chat/Chat_ItemRenderer.js",
	"bin-debug/components/chat/System_notice.js",
	"bin-debug/components/chengzhuang/CJ_assembly_item.js",
	"bin-debug/components/chengzhuang/CJ_assembly.js",
	"bin-debug/components/chengzhuang/CJ_tab.js",
	"bin-debug/components/common/AddGoodsNumCom.js",
	"bin-debug/components/common/CommonItem.js",
	"bin-debug/components/common/Forging_AttrItem.js",
	"bin-debug/components/common/GlobalFunc.js",
	"bin-debug/components/common/MovieClip.js",
	"bin-debug/components/common/SkillEffect.js",
	"bin-debug/components/common/UI_ConnectWord.js",
	"bin-debug/components/friends/Friend_chat_item.js",
	"bin-debug/components/friends/Friends_list_item.js",
	"bin-debug/components/friends/Friends_popup.js",
	"bin-debug/components/fuben/fuben_material_item.js",
	"bin-debug/components/itemRenderers/ForgingItemRenderer.js",
	"bin-debug/components/level/level_btn.js",
	"bin-debug/components/level/level_info.js",
	"bin-debug/components/level/level_rank_item.js",
	"bin-debug/components/mail/Mail_itemRenderer.js",
	"bin-debug/components/mail/Mail_popup.js",
	"bin-debug/components/mainUI/MainUI_nav.js",
	"bin-debug/components/mainUI/MainUI_progress.js",
	"bin-debug/components/mainUI/MainUI_roleInfo.js",
	"bin-debug/components/mainUI/MainUI_title.js",
	"bin-debug/components/map/MapUnit_Drop.js",
	"bin-debug/components/map/MapUnit_Monster.js",
	"bin-debug/components/map/MapUnit_Role.js",
	"bin-debug/components/rank/Rank_roleInfo_item.js",
	"bin-debug/components/roleInfo/fashion/Role_fashion.js",
	"bin-debug/components/roleInfo/longhunhudun/Get_Goods_pop.js",
	"bin-debug/components/roleInfo/longhunhudun/Role_longhunhudun.js",
	"bin-debug/components/roleInfo/longhunhudun/Role_specialItem.js",
	"bin-debug/components/roleInfo/longhunhudun/Way_other_item.js",
	"bin-debug/components/roleInfo/longhunhudun/Way_shop_item.js",
	"bin-debug/components/roleInfo/meridians/RoleMeridiansTab.js",
	"bin-debug/components/roleInfo/reborn/Role_getXw.js",
	"bin-debug/components/roleInfo/reborn/Role_reborn.js",
	"bin-debug/components/roleInfo/reborn/Role_xwExchange_item.js",
	"bin-debug/components/roleInfo/Role_headCom.js",
	"bin-debug/components/roleInfo/Role_showAttrs.js",
	"bin-debug/components/roleInfo/RoleEquipRenderer.js",
	"bin-debug/components/roleInfo/RoleHeadItemRender.js",
	"bin-debug/components/roleInfo/RoleTab.js",
	"bin-debug/components/roleInfo/select/Role_select_item.js",
	"bin-debug/components/skill/Material_find.js",
	"bin-debug/components/skill/Material_item.js",
	"bin-debug/components/skill/RoleSkillItemRender.js",
	"bin-debug/components/skill/Secret_book.js",
	"bin-debug/components/skill/Secret_replace.js",
	"bin-debug/components/skill/SkillShowTab.js",
	"bin-debug/components/store/Store_item.js",
	"bin-debug/components/store/Store_shop.js",
	"bin-debug/components/tips/PopTips.js",
	"bin-debug/components/tips/PowerTips.js",
	"bin-debug/components/tips/RedPointTips.js",
	"bin-debug/components/wing/Wing_star_item.js",
	"bin-debug/components/wing/WingTab.js",
	"bin-debug/config/Config.js",
	"bin-debug/data/DataCenter.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/components/bag/Bag_addGrid.js",
	"bin-debug/data/proto/MessageType.js",
	"bin-debug/data/proto/messType.js",
	"bin-debug/components/bag/Bag_item.js",
	"bin-debug/data/proto/Proto.js",
	"bin-debug/data/temple/AddBagTemple.js",
	"bin-debug/data/temple/BossTemple.js",
	"bin-debug/data/temple/BuffTemple.js",
	"bin-debug/data/temple/CheatsInlayTemple.js",
	"bin-debug/data/temple/CheatsOpenTemple.js",
	"bin-debug/data/temple/CheatsTemple.js",
	"bin-debug/data/temple/DragonSoulTemple.js",
	"bin-debug/data/temple/DropItemTemple.js",
	"bin-debug/data/temple/DropTemple.js",
	"bin-debug/data/temple/EquipTemple.js",
	"bin-debug/data/temple/ExperienceTemple.js",
	"bin-debug/data/temple/FashionTemple.js",
	"bin-debug/data/temple/FeatureTemple.js",
	"bin-debug/data/temple/FilterWordTemple.js",
	"bin-debug/data/temple/GemstoneTemple.js",
	"bin-debug/components/bag/Bag_smeltEquipSelect.js",
	"bin-debug/data/temple/GridrateTemple.js",
	"bin-debug/data/temple/GridTemple.js",
	"bin-debug/data/temple/HumenTemple.js",
	"bin-debug/data/temple/InitializeTemple.js",
	"bin-debug/data/temple/ItemTemple.js",
	"bin-debug/data/temple/JingMaiTemple.js",
	"bin-debug/data/temple/JobInitTemple.js",
	"bin-debug/data/temple/LevelStageTemple.js",
	"bin-debug/data/temple/LevelTemple.js",
	"bin-debug/data/temple/MailTemple.js",
	"bin-debug/data/temple/MapTemple.js",
	"bin-debug/data/temple/MeetBattleTemple.js",
	"bin-debug/data/temple/MonsterAITemple.js",
	"bin-debug/data/temple/MonsterTemple.js",
	"bin-debug/data/temple/PeerageTemple.js",
	"bin-debug/data/temple/RankTemple.js",
	"bin-debug/data/temple/RebornBossTemple.js",
	"bin-debug/data/temple/RebornTemple.js",
	"bin-debug/data/temple/RoleInitTemple.js",
	"bin-debug/data/temple/ScoreTemple.js",
	"bin-debug/data/temple/ShieldTemple.js",
	"bin-debug/data/temple/ShopTemple.js",
	"bin-debug/data/temple/SkillTemple.js",
	"bin-debug/data/temple/StrengthenTemple.js",
	"bin-debug/data/temple/TalismanTemple.js",
	"bin-debug/data/temple/TaskTemple.js",
	"bin-debug/components/bag/BagBtn.js",
	"bin-debug/data/temple/TitleTemple.js",
	"bin-debug/data/temple/UnitTemple.js",
	"bin-debug/data/temple/WingsTemple.js",
	"bin-debug/data/temple/WordTemple.js",
	"bin-debug/data/temple/ZhuLingTemple.js",
	"bin-debug/data/TempleManager.js",
	"bin-debug/data/vo/MapConfigVo.js",
	"bin-debug/data/vo/PlayerBaseInfoVo.js",
	"bin-debug/data/vo/RoleInfoVo.js",
	"bin-debug/display/MainContainer.js",
	"bin-debug/display/View_selectServer.js",
	"bin-debug/display/ViewController.js",
	"bin-debug/enums/MapUnitState.js",
	"bin-debug/enums/ModuleEnum.js",
	"bin-debug/enums/TipsEnum.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/Main.js",
	"bin-debug/manager/AssetsManager.js",
	"bin-debug/manager/ModuleManager.js",
	"bin-debug/manager/PopTipsManager.js",
	"bin-debug/manager/PopUpManager.js",
	"bin-debug/module/action/Module_action.js",
	"bin-debug/module/bag/Module_bag.js",
	"bin-debug/module/bag/smelt/Module_bag_smelt.js",
	"bin-debug/module/bag/smelt/View_bag_smelt.js",
	"bin-debug/module/bag/View_bag.js",
	"bin-debug/module/boss/Module_boss.js",
	"bin-debug/module/boss/View_boss.js",
	"bin-debug/module/chat/Module_chat.js",
	"bin-debug/module/chat/View_chat.js",
	"bin-debug/module/chengzhuang/Module_chengzhuang.js",
	"bin-debug/module/chengzhuang/View_chengzhuang.js",
	"bin-debug/module/data/Module_data.js",
	"bin-debug/module/forging/dataUtil/Forging_DataUtil.js",
	"bin-debug/module/forging/Module_forging.js",
	"bin-debug/module/forging/popup/Forging_getStone.js",
	"bin-debug/module/forging/View_forging.js",
	"bin-debug/module/friends/Module_friends.js",
	"bin-debug/module/friends/View_friends.js",
	"bin-debug/module/fuben/Module_fuben.js",
	"bin-debug/module/fuben/View_fuben.js",
	"bin-debug/module/level/Module_level.js",
	"bin-debug/module/level/View_level.js",
	"bin-debug/module/mail/Module_mail.js",
	"bin-debug/module/mail/View_mail.js",
	"bin-debug/module/map/layer/View_map_bg.js",
	"bin-debug/module/map/layer/View_map_effect.js",
	"bin-debug/module/map/layer/View_map_unit.js",
	"bin-debug/module/map/Module_map.js",
	"bin-debug/module/map/View_map.js",
	"bin-debug/module/player/Module_player.js",
	"bin-debug/module/rank/Module_rank.js",
	"bin-debug/module/rank/View_rank.js",
	"bin-debug/module/roleInfo/Module_roleInfo.js",
	"bin-debug/module/roleInfo/select/Module_roleSelect.js",
	"bin-debug/module/roleInfo/select/View_roleSelect.js",
	"bin-debug/module/roleInfo/View_roleInfo.js",
	"bin-debug/module/skill/Module_skillPanel.js",
	"bin-debug/module/skill/View_skillPanel.js",
	"bin-debug/module/store/Module_store.js",
	"bin-debug/module/store/View_store.js",
	"bin-debug/module/ui/mainUI/Module_mainUI.js",
	"bin-debug/module/ui/mainUI/View_mainUI.js",
	"bin-debug/module/ui/selectRole/Module_selectRole.js",
	"bin-debug/module/ui/selectRole/View_selectRole.js",
	"bin-debug/net/Processor.js",
	"bin-debug/net/SocketManager.js",
	"bin-debug/notice/MainNotify.js",
	"bin-debug/test/ChangeEvent.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/utils/ActionUtil.js",
	"bin-debug/utils/AttrNameUtil.js",
	"bin-debug/components/bag/equipPop/Attr_baseInfo.js",
	"bin-debug/utils/Global.js",
	"bin-debug/utils/LListener.js",
	"bin-debug/utils/MoviePool.js",
	"bin-debug/utils/PosUtils.js",
	"bin-debug/utils/TimerUtils.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "showAll",
		contentWidth: 480,
		contentHeight: 800,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:12,textColor:0xffffff,bgAlpha:0.9",
		showLog: true,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};